# Generated by Django 3.0.7 on 2020-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nameareaen', models.CharField(max_length=155)),
                ('nameareaes', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('idcompetence', models.AutoField(primary_key=True, serialize=False)),
                ('codecompetence', models.CharField(max_length=5)),
                ('namecompetenceen', models.CharField(max_length=155)),
                ('namecompetencees', models.CharField(max_length=155)),
                ('descriptioncompetenceen', models.CharField(max_length=350)),
                ('descriptioncompetencees', models.CharField(max_length=350)),
            ],
            options={
                'db_table': 'competences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competenciasusuario',
            fields=[
                ('idregistrocompusuario', models.AutoField(primary_key=True, serialize=False)),
                ('tiene', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competenciasusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('idexample', models.AutoField(primary_key=True, serialize=False)),
                ('titlescenarioen', models.CharField(max_length=155)),
                ('titlescenarioes', models.CharField(max_length=155)),
                ('objectivescenarioen', models.CharField(max_length=155)),
                ('objectivescenarioes', models.CharField(max_length=155)),
                ('descriptionexampleen', models.CharField(max_length=780)),
                ('descriptionexamplees', models.CharField(max_length=780)),
            ],
            options={
                'db_table': 'examples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('idgroup', models.AutoField(primary_key=True, serialize=False)),
                ('namegroupen', models.CharField(max_length=50)),
                ('namegroupes', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linecompetences',
            fields=[
                ('idline', models.AutoField(primary_key=True, serialize=False)),
                ('verben', models.CharField(max_length=100)),
                ('verbes', models.CharField(max_length=100)),
                ('keywordsen', models.CharField(max_length=100)),
                ('keywordses', models.CharField(max_length=100)),
                ('linecompetenceen', models.CharField(max_length=350)),
                ('linecompetencees', models.CharField(max_length=350)),
            ],
            options={
                'db_table': 'linecompetences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proficiencylevels',
            fields=[
                ('idlevel', models.AutoField(primary_key=True, serialize=False)),
                ('namelevelen', models.CharField(max_length=50)),
                ('nameleveles', models.CharField(max_length=50)),
                ('descriptionlevelen', models.CharField(max_length=155)),
                ('descriptionleveles', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'proficiencylevels',
                'managed': False,
            },
        ),
    ]
