# Generated by Django 3.0.7 on 2020-06-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competenciasusuario',
            fields=[
                ('idregistrocompusuario', models.AutoField(primary_key=True, serialize=False)),
                ('tiene', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competenciasusuario',
                'managed': False,
            },
        ),
    ]
