# Generated by Django 3.0.7 on 2020-06-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_competenciasusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
